# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5cf201c1c7697c3cc892d1e2edc421fa9fa83f5e906bd77a9859ffb67bcf0d842aca81aaa6b3f14eb65e97ec3c23b1583f37cb3075669a0dffae8d3672322f18

test:
  secret_key_base: 96948a1926e725746f0ea287d3967ed36d10b7dfc1b0d677759995a74c6c6d0a426ee4c2b28be0db9a058fecf344cc296d5881354cd52895298f66c3e3f05021

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
